version: '3.7'
services:
    #facciamo partire un container nella rete tap con zookeper attivo
    zookeeper:
        image: tap:kafka
        container_name: kafkaZK
        environment:
            - KAFKA_ACTION=start-zk
        networks: 
            tap:
                ipv4_address: 10.0.100.22
     #facciamo partire un container nella rete tap con Kafka server attivo
    kafkaserver:
        image: tap:kafka
        container_name: kafkaServer
        environment:
            - KAFKA_ACTION=start-kafka
            #- KAFKA_HEAP_OPTS=-Xmx256M
        ports:
            - 9092:9092
        networks: 
            tap:
                ipv4_address: 10.0.100.23
        depends_on:
            - zookeeper
     #facciamo partire l'interfaccia grafica di Kafka 
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafkaWebUI
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafkaServer:9092
        ports: 
            - 8082:8080
        networks: 
            - tap
        depends_on:
            - kafkaserver
        #facciamo partire un container(su cui montiamo il volume dove vogliamo i log) nella rete tap dove sarà attivo nginx 
   

    #facciamo partire un container con logstash 
    #su di esso montiao il file nginx.conf all'internod i logstash.conf
    #in nginx.conf abbiamo settato come sorgente il file condiviso access.log e come destinazione kafka 
    logstash:
        #depends_on:
         #   - nginx
        image: tap:logstash
        ports: 
            - 8081:8080
        networks: 
            - tap
        environment:
            XPACK_MONITORING_ENABLED: "false"
        volumes:
            - ngnix_logs:/var/log/nginx
            - ./logstash/pipeline/nginx.conf:/usr/share/logstash/pipeline/logstash.conf

 #qui settiamo il volume all'interno della rete            
volumes:
    ngnix_logs:
networks:
    tap:
        name: tap
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.100.1/24
        external: true

#     export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"